---
baseurl: "https://padlock.io/"
title: "Padlock - A Minimalist Password Manager"
languageCode: "en-us"
params:
    androidUrl: https://play.google.com/store/apps/details?id=com.maklesoft.padlock
    iosUrl: https://itunes.apple.com/app/id871710139
    chromeUrl: https://chrome.google.com/webstore/detail/padlock/npkoefjfcjbknoeadfkbcdpbapaamcif
    githubUrl: http://github.com/maklesoft/padlock/
